<?xml version='1.0' encoding="UTF-8"?>

<!DOCTYPE MIB [
<!ELEMENT MIB (MibTable)>
<!ELEMENT MibTable (MibNode)>
<!ELEMENT MibNode (EnumValue)>

<!ATTLIST MIB  
	MibFiles CDATA #REQUIRED  
	ResourceBundle CDATA  #REQUIRED
	ReInitSnmp CDATA "false"	
>

<!ATTLIST MibTable  
	Name   			ID 		#REQUIRED
	Type   			CDATA 	"Table"
	Column			CDATA  	"1"
	Height			CDATA  	"22"   
	LabelWidth		CDATA  	"200"
	ValueWidth		CDATA  	"200"
	XInterval		CDATA  	"4"
	YInterval		CDATA  	"2"
	MaxColWidth		CDATA  	"80"
	Align			CDATA  	"CENTER"
	UseExtendStyle  CDATA   "true"
>
<!ATTLIST MibNode  
	Logic  	 CDATA 	#REQUIRED
	Physics  CDATA 	#REQUIRED
	Unit	 CDATA  ""
	Checker  CDATA  ""
	MibNodeAdapter CDATA  ""
>
<!ATTLIST EnumValue  
	Value ID #REQUIRED  
	Label CDATA #REQUIRED 
>

]>
 
<MIB  ResourceBundle = "com/raisecom/ems/epon/client/resource/oam/Resource" MibProfile = "com/raisecom/ems/eponcommon/server/modules/cfgmgt/profile/1.44/eponv2.rmp" >
 
   <MibTable Name="rfc1213 System Group" Type="List" Column="1" Height="22" LabelWidth="200" ValueWidth="200" XInterval="4" YInterval="2" MaxColWidth="80" Align="CENTER" UseExtendStyle="true">
    <MibNode Logic="sysObjectID" Physics="sysObjectID.0" Unit="" Checker="" MibNodeAdapter="" />
  </MibTable>
	
  <MibTable Name="raisecomShelfTable" Type="List" ModifyRefresh="true" Column="1" Height="22" LabelWidth="200" ValueWidth="200" XInterval="4" YInterval="2" MaxColWidth="80" Align="CENTER" UseExtendStyle="true">
    <MibNode Logic="raisecomShelfTemperature" Physics="raisecomShelfTemperature.0" ValueAdapter="com.raisecom.ems.eponcommon.client.onu.devicemgt.adapter.CentigradeAndFahrenheitTemperatureValueAdapter" SyntaxName="STRING" Unit="unit.centigradeAndFahrenheitTemperature" Checker="" MibNodeAdapter="" />
  </MibTable>
	
  <MibTable Name="SwitchInformation" Type="List" ModifyRefresh="true" ValueWidth="240" Column="1" Height="22" LabelWidth="200" XInterval="4" YInterval="2" MaxColWidth="80" Align="CENTER" UseExtendStyle="true">
    <MibNode Logic="rcSwitchRoseVersion" Physics="rcSwitchRoseVersion.0" Unit="" Checker="" MibNodeAdapter="">
      <MibNodeAdapter Class="com.raisecom.ems.templet.server.adapter.OctetStringMibNodeAdapter" />
    </MibNode>
  </MibTable>
  
  <MibTable Name = "raisecomSlotTable" Type = "Table"> 	  
	<MibNode Logic = "raisecomSlotId" 	                              Physics = "raisecomSlotId"/>
	<MibNode Logic = "raisecomSlotExpectCardType" 	                  Physics = "raisecomSlotExpectCardType" Access = "ROnly"
		PanelClass = "com.raisecom.ems.eponcommon.client.olt.devicemgt.panel.SlotCardTypePanel">
        <EnumValue Value = "2"    Label = "NULL" />
		<EnumValue Value = "1101" Label = "SMC" />
		<EnumValue Value = "1102" Label = "2PON" />
		<EnumValue Value = "1105" Label = "4PON" />
		<EnumValue Value = "1103" Label = "4GE" />
		<EnumValue Value = "1104" Label = "2GE" />
		<!--ValueAdapter Class = "com.raisecom.ems.eponcommon.client.olt.devicemgt.adapter.SlotInfoValueAdapter"/-->		
	</MibNode>
	<MibNode Logic = "raisecomSlotActCardState" 	                  Physics = "raisecomSlotActCardState" />
  </MibTable>
	
	<MibTable Name = "rcCpuMonTable" Type = "List" >
		<MibNode Logic = "raisecomCPUUtilizationTotal" 								Physics = "raisecomCPUUtilizationTotal.0" SyntaxName="String"/> 
	</MibTable>

	<MibTable Name = "raisecomPowerOutputTable" Type = "Table" ModifyRefresh = "true">
		<MibNode Logic = "raisecomPowerDeviceIndex" 				Physics = "raisecomPowerDeviceIndex"  Access = "noaccess" IsIndex = "true"/>
		<MibNode Logic = "raisecomPowerOutputType" 					Physics = "raisecomPowerOutputType" Access = "noaccess" IsIndex = "true"/>
		<MibNode Logic = "raisecomPowerStatus" 				        Physics = "raisecomPowerStatus">
			<EnumValue Value = "1" Label = "alarm_normal" />
			<EnumValue Value = "2" Label = "alarm_abnormal" />
			<EnumValue Value = "3" Label = "alarm_null" />
			<EnumValue Value = "4" Label = "alarm_highAlarm" />
			<EnumValue Value = "5" Label = "alarm_lowAlarm" />
		</MibNode>
	</MibTable>
	
	 <!--  版本信息表 -->
	  <MibTable Name = "raisecomSWFileTable" Type = "Table">
		<MibNode Logic = "raisecomSWFileVersion" 	            Physics = "raisecomSWFileVersion"/>
	  </MibTable>
	
  <MibTable Name="raisecomFanTable" Type="Table" PageSize="25" Column="1" Height="22" LabelWidth="200" ValueWidth="200" XInterval="4" YInterval="2" MaxColWidth="80" Align="CENTER" UseExtendStyle="true">
    <MibNode Logic="raisecomFanIndex" Physics="raisecomFanIndex" OrderType="Integer" Access="noaccess" Unit="" Checker="" MibNodeAdapter="" />
    <MibNode Logic="raisecomFanStatus" Physics="raisecomFanStatus" Unit="" Checker="" MibNodeAdapter="" />
  </MibTable>
	
  <MibTable Name="rcVlanCfgPortTable" Type="Table" PageSize="25" ModifyRefresh="true" Column="1" Height="22" LabelWidth="200" ValueWidth="200" XInterval="4" YInterval="2" MaxColWidth="80" Align="CENTER" UseExtendStyle="true">
    <MibNode Logic="rcPortIndex" Physics="rcPortIndex" OrderType="Integer" Access="noaccess" IsIndex="true" Unit="" Checker="" MibNodeAdapter="" />
	<MibNode Logic="rcPortMode" Physics="rcPortMode" Unit="" Checker="" MibNodeAdapter="">
      <EnumValue Value="1" Label="access" />
      <EnumValue Value="2" Label="trunk" />
    </MibNode>
    <MibNode Logic="rcPortTrunkAllowVlanList" Physics="rcPortTrunkAllowVlanList" Unit="" Checker="" MibNodeAdapter="">
      <MibNodeAdapter Class="com.raisecom.adapter.VlansetAdapter" />
    </MibNode>
  </MibTable>

	<!--liujs add -->
	<MibTable Name="rcHighAvailabilityTable" Type = "Table">
		<MibNode Logic="rcHighAvailabilitySwitchedCount" Physics="rcHighAvailabilitySwitchedCount"></MibNode>
	</MibTable>
	<MibTable Name="rcPortIsolateTable" Type = "Table">
		<MibNode Logic="rcPortIsolateGroupId" Physics="rcPortIsolateGroupId"></MibNode>
		<MibNode Logic="rcPortIsolateGroupPortList" Physics="rcPortIsolateGroupPortList">
			<ValueAdapter Class = "com.raisecom.adapter.TrunkGroupPortListValueAdapter" SlotMax = "22" SlotMin = "1" PortMax = "16" PortMin = "1"/>
			<MibNodeAdapter Class = "com.raisecom.adapter.TrunkPortListMibNodeAdapter" />
		</MibNode>
	</MibTable>
	<MibTable Name = "raisecomShelfTable2" Type="List" ModifyRefresh = "true">
		<MibNode Logic = "raisecomShelfPrimaryNMSSlotId" 	Physics = "raisecomShelfPrimaryNMSSlotId"/>
		<MibNode Logic = "raisecomShelfSecondaryNMSSlotId" 	Physics = "raisecomShelfSecondaryNMSSlotId"/>
	</MibTable>
	<MibTable Name = "raisecomCardPowerTable" Type = "Table">
		<MibNode Logic = "raisecomCardPowerSlotId" 				Physics = "raisecomCardPowerSlotId"  />
		<MibNode Logic = "raisecomCardPowerType" 		        Physics = "raisecomCardPowerType" >
			<EnumValue Value = "1" Label = "0.75v" />
			<EnumValue Value = "2" Label = "0.9v" />
			<EnumValue Value = "3" Label = "1v" />
			<EnumValue Value = "4" Label = "1.2v" />
			<EnumValue Value = "5" Label = "1.5v" />
			<EnumValue Value = "6" Label = "1.8v" />
			<EnumValue Value = "7" Label = "2.5v" />
			<EnumValue Value = "8" Label = "3.3v" />
			<EnumValue Value = "9" Label = "4.8v" />
			<EnumValue Value = "10" Label = "5v" />
			<EnumValue Value = "11" Label = "5.2v" />
			<EnumValue Value = "12" Label = "12v" />
			<EnumValue Value = "13" Label = "unkown" />
			<EnumValue Value = "14" Label = "null" />
			<EnumValue Value = "15" Label = "1.25v" />
			<EnumValue Value = "16" Label = "2.9v" />
		</MibNode>
		<MibNode Logic = "raisecomCardPowerVolValue" 			Physics = "raisecomCardPowerVolValue" Unit = "0.001v"/>
	</MibTable>

	<!--ONU在线状态、上一次掉电原因-->
	<MibTable Name="rcEponONUTable" Type="Table">
		<MibNode Logic="rcEponONUIndex" Physics="rcEponONUIndex"/>
		<MibNode Logic="rcEponONUWorkStatus" Physics="rcEponONUWorkStatus"/>
		<MibNode Logic="rcEponONUOfflineReason" Physics="rcEponONUOfflineReason"/>
	</MibTable>
	<MibTable Name = "rcCardProtectTable" Type = "Table">
		<MibNode Logic = "rcCardProtectGroupIndex" 	                      Physics = "rcHighAvailabilityIndex"/>
		<MibNode Logic = "rcCardProtectGroupMajorCardSlotIndex" 	                  Physics = "rcHighAvailabilityMajorSlot" ModifyDisp = "false"/>
		<MibNode Logic = "rcCardProtectGroupMajorCardState" 	          Physics = "rcHighAvailabilityMajorSlotState" />
		<MibNode Logic = "rcCardProtectGroupMinorCardSlotIndex"                    Physics = "rcHighAvailabilityMinorSlot" ModifyDisp = "false"/>
		<MibNode Logic = "rcCardProtectGroupMinorCardState" 	          Physics = "rcHighAvailabilityMinorSlotState" />
		<MibNode Logic = "rcCardProtectGroupOperState" 	                  Physics = "rcHighAvailabilityOperState" />
		<MibNode Logic = "rcCardProtectGroupForcedSwitch"                 Physics = "rcHighAvailabilityForcedSwitch" AddDisp = "false" ModifyDisp = "false" IsHide="true" />
		<MibNode Logic = "rcCardProtectGroupSwitchResult" 	              Physics = "rcHighAvailabilitySwitchResult">
			<EnumValue Value="0" Label="enum.default"/>
			<EnumValue Value="1" Label="enum.succeeded"/>
			<EnumValue Value="2" Label="enum.destFailure"/>
		</MibNode>
		<MibNode Logic = "rcCardProtectGroupSwitchTime" 	              Physics = "rcHighAvailabilitySwitchTime"/>
		<MibNode Logic = "rcHighAvailabilitySwitchReason"                 Physics = "rcHighAvailabilitySwitchReason"/>
		<MibNode Logic = "rcHighAvailabilitySwitchedCount"                Physics = "rcHighAvailabilitySwitchedCount"/>
	</MibTable>

	<MibTable Name = "raisecomCpuV2Table" Type = "Table">
		<MibNode Logic = "raisecomCpuUsage1SecondV2" 	                      Physics = "rcCpuUtilizationTotal" Unit="%" />
		<MibNode Logic = "raisecomTotalMemoryV2" 	                      Physics = "rcMemoryTotoalMemory" Unit="B"/>
		<MibNode Logic = "raisecomAvailableMemoryV2" 	                      Physics = "rcMemoryAvailableMemory" Unit="B"/>
	</MibTable>
	<MibTable Name="rcGponONUTable">
		<MibNode Logic="rcGponONUIndex" Physics="rcGponONUIndex"/>
		<MibNode Logic="rcGponONUWorkStatus" Physics="rcGponONUWorkStatus"/>
		<MibNode Logic="rcGponONUOfflineReason" Physics="rcGponONUOfflineReason"/>
	</MibTable>
	<!--ONU下挂 Mac地址数-->
	<MibTable Name="rcGponOnuMacAddrTable">
		<MibNode Logic="rcGponOnuEthPortIndex"                    Physics="rcGponOnuEthPortIndex" />
		<MibNode Logic="rcGponOnuMacAddrList" Physics="rcGponOnuMacAddrList"/>
		<MibNode Logic="rcGponOnuMacAddrCount" Physics="rcGponOnuMacAddrCount"/>
	</MibTable>
	<MibTable Name = "rcEponOnuMacStatTable" Type = "Table">
		<MibNode Logic = "rcEponOnuDevIndex" 		  Physics = "rcEponOnuDevIndex" />
		<MibNode Logic = "rcEponOnuMacNum" 	          Physics = "rcEponOnuMacNum"  />
	</MibTable>
	<!--ONU接收到的光功率-->
	<MibTable Name = "rcGponOnuPonMngTable" Type = "Table"   LabelWidth="350" >
		<MibNode Logic="rcGponOnuPonPortIndex"                 Physics="rcGponOnuPonPortIndex">
		</MibNode>
		<MibNode Logic = "rcGponOnuPonRxPower"			Physics = "rcGponOnuPonRxPower" />
	</MibTable>
	<MibTable Name="rcEponTransceiverMonitorTable">
		<MibNode Logic="rcEponTransceiverIndex" Physics="rcEponTransceiverIndex"/>
		<MibNode Logic="rcEponTransceiverMonitorValue" Physics="rcEponTransceiverMonitorValue"/>
	</MibTable>
	<!--liujs add end-->
</MIB>
